# Generated by Django 2.2.7 on 2020-02-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='goods',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dark.Goods', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shopcar',
            unique_together={('user', 'goods')},
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='click',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='good_no',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='thumb_path',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='title',
        ),
    ]
